Repository bsoyka/secrecy, pull requests merged in 2018-10, with the labels that each got.

#4 Create LICENSE
  LICENSE
Labels: enhancement

#5 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#6 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#10 Added error-handling for checking key
  main.py
Labels: bug

#12 Create README.md
  README.md
Labels: enhancement

#16 #2 Add setup.py and modularize
  MANIFEST.in
  TESTING_INSTRUCTIONS.md
  main.py
  secrecy/__init__.py
  secrecy/main.py
  secrecy/secrecy.py
  setup.py
Labels: enhancement, hacktoberfest
